#!/bin/bash

# Need one and only one parameter
if [ $# -ne 1 ]; then
  echo "Usage: $0 <new branch name>"
  echo "No spaces or such funny characters are allowed."
  exit 1
fi

# Make sure we're inside a git directory
git status >/dev/null 2>&1
if [ $? -ne 0 ]; then
  echo "error: run this script from inside a git repository"
  exit 1
fi

BRANCH=`git rev-parse --abbrev-ref HEAD`

isMaster=`expr "$BRANCH" : 'master'`
isRelease=`expr "$BRANCH" : 'release'`

if [ $isMaster -eq 0 ] && [ $isRelease -eq 0 ]; then
  echo "WARNING - you're starting a new branch from $BRANCH"
  echo "That doesn't look like a master or release branch!"
  read -p "Hit ctrl-c to cancel, or RETURN to continue" choice
fi

git checkout -b $1
mkdir $1
cd $1
mkdir -p images projects/starter projects/final projects/challenge
touch images/.keep projects/starter/.keep projects/final/.keep projects/challenge/.keep
cat << EOF > $1.markdown
## $1

Hi, welcome to your markdown document!

EOF
cd ..
git add $1
git commit -m "Adding $1" $1
git checkout $BRANCH

echo Added directory, branch, and initial commit for "$1".
echo "You're now back on the '$BRANCH' branch."

